### ISSUE TITLE
Wrong link under "Let's chat"

### ISSUE THREAD

**Issue by MaxKaay** [0xHabitat/website#6]
There is a wrong link: https://calendly.com/deora-earth/intro

That's the right one: https://calendly.com/deora_earth/intro

![image](https://user-images.githubusercontent.com/45236782/85282720-7d5eb000-b48c-11ea-861a-a4305241ef91.png)

**Comment by johba37** [comment]
fixed here: https://github.com/deora-earth/website/commit/029692d5da5fc1c073f7efd7c2686025b4a027d0
